// src/firebase/config.ts
import { FirebaseOptions } from 'firebase/app';

// This file is automatically generated by the Firebase setup tool.
// Do not edit this file manually.

export const firebaseConfig: FirebaseOptions = {
  "projectId": "studio-3459896286-b66ef",
  "appId": "1:646798820844:web:68351997f574e241572cc9",
  "apiKey": "AIzaSyBmqGNIYG4gpDwoVA86v8J-RcAP1SP5cJc",
  "authDomain": "studio-3459896286-b66ef.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "646798820844"
};
